# Generated by Django 5.0.6 on 2024-06-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='task_detail',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
