# Generated by Django 5.0.6 on 2024-06-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_remove_task_tasks_task_task_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_detail',
            field=models.CharField(max_length=1000),
        ),
    ]
