# Generated by Django 5.0.6 on 2024-06-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0003_alter_task_task_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_detail',
        ),
        migrations.AddField(
            model_name='task',
            name='task_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
